### ISSUE TITLE
Retour de test de création module / Doc

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_modulator#100]
Par @jacquesfize : 

# Analyse de Modulator

## Introduction

L'objectif derrière `modulator` est de permettre à des utilisateurs avec peu de connaissances en programmation de faire ses propres modules dans GeoNature. Pour la mise en pratique, le développement de l'outil s'accompagne de la mise en place du sous-module SIPAF, pour Système d’information sur les Passages à Faune. Le SIPAF permet de recueillir les données relatives aux passages à faune gérées par les acteurs et gestionnaires des infrastructures de transport terrestres. Son objectif est notamment de contribuer à la connaissance nationale de l'effet fragmentant des infrastructures linéaires de transport et d'évaluer la réponse apportée par les passages à faune sur la biodiversité. Il doit ainsi permettre de mieux connaître les priorités d'intervention en matière de restauration des continuités écologiques.

Dans ce document, je reviendrais sur mon experience sur l'installation, l'utilisation et la création de sous-module dans MODULATOR.

**SOMMAIRE**

1.  Installation de MODULATOR
2.  Installation de SIPAF
3.  Mise à jour de SIPAF
4.  Création d'un sous-module
    1. Arborescence du dossier d'un sous-module
    2. Utilisation d'un template
    3. Configuration du module
    4. Définition du modèle de données
    5. Définition des permissions
    6. Création du Frontend
5.  Commandes disponibles

## Installation de MODULATOR

Très simple, il suffit de cloner ou télécharger le module depuis github

```shell
git clone git@github.com:PnX-SI/gn_modulator.git
# OU
wget https://github.com/PnX-SI/gn_modulator/archive/refs/tags/x.y.z.zip
```

Une fois téléchargé, activé le virtualenv de votre instance de GeoNature et installé modulator à l'aide de la commande dédiée : `geonature install-gn-module <pathtomoduledir> <modulecode>`

```shell
source /pathtoyourGeoNature/backend/venv/bin/activate
geonature install-gn-module <pathtomodulator> MODULATOR
```

## Installation de SIPAF

L'installation de SIPAF s'effectue à l'aide d'une commande dédiée dans Modulator : `geonature modulator install -p <submodulepath>`. Dans le cas de SIPAF, celui-ci se trouve dans le dossier `contrib` du dossier du module de Modulator (`gn_modulator/contrib/m_sipaf`). L'installation se fait de la manière suivante :

```shell
# Si ce n'est pas déjà fait, activer le virtualenv de votre GeoNature
geonature modulator install -p <pathto_gn_modulator>/contrib/m_sipaf
```

## Mise à jour de SIPAF+gn_modulator

Si votre dossier contenant Modulator a été téléchargé à l'aide Git, il suffit de mettre à jour la branche principale (ou autre) à l'aide d'un `git pull`. Dans le cas, où vous avez téléchargé l'archive, la marche à suivre est la suivante (si on s'en référe au README sur GitHub).

```shell
# Comme toujours, vérifier que vous êtes bien sur le venv de GeoNature
wget https://github.com/PnX-SI/gn_modulator/archive/refs/tags/x.y.z.zip
unzip x.y.z.zip
mv <current_modulator_dir> old_<current_modulator_dir>
mv gn_modulator-x.y.z <current_modulator_dir>
pip install -e <current_modulator_dir>/contrib/m_sipaf/.
```

Pour mettre à jour, il suffit de relancer l'installation de MODULATOR à l'aide de la commande :

```shell
geonature install-gn-module <current_modulator_dir> MODULATOR
```

Il se peut que certaines revision alembic ne soit pas appliquer, vous pouvez le vérifier à l'aide de la commande `geonature db status`. Si c'est le cas, il suffit de lancer la commande suivante : `geonature db autoupgrade`.

**Note** La manipulation obligatoire lors de la mise à jour du couple Modulator + SIPAF vient du changement de dossier et la perte de lien symbolique entre alembic et les révisions de SIPAF. Une solution envisagée est de déplacer le sous-module de SIPAF dans un dépôt GitHub qui lui est consacré.

## Création d'un sous-module

Dans cette section, je reviendrais sur mon expérience sous forme de documentation quand à la création d'un sous-module de Modulator.

### Arboresence du dossier d'un sous-module

Le diagramme ci-dessous présente l'arborescence de dossier et fichier nécessaire à la création d'un sous-module.

- backend
  <span style="color:red">Contient la déclaration de la BDD en SQLA, les routes Flask supprlémentaires si besoin, les révisions alembic nécessairent à l'initialisation/évolution de la BDD.</span>
  - <nom_module>
    - migrations
      - \_\_init\_\_.py
      - versions <span style="color:red"> Contient les révisions alembic</span>
        - \_\_init\_\_.py
    - \_\_init\_\_.py
    - blueprint.py <span style="color:red">Permet d'ajouter des routes additionnelles</span>
    - conf_schema_toml.py <span style="color:red">Si fichier de configuration donné</span>
    - models.py <span style="color:red">Contient la déclaration des tables en SQLAlchemy de votre modèle</span>
- config
  <span style="color:red">Ensemble de méta-données utilisées par modulator pour définir votre modèle, le fonctionnement de votre export, de votre import, mais aussi la définition des layouts des différents pages composant votre frontend</span>
  - assets <span style="color:red">Contient des fichiers statiques (images,etc.) </span>
  - definitions <span style="color:red">Contient les définitions des différentes tables en YAML</span>
  - exports <span style="color:red"> Contient les fichiers de configurations pour l'import et l'export de données dans votre sous-module.</span>
  - features <span style="color:red"> Contient plusieurs fichiers permettant de peupler la base de données avec des données initiales (par ex. les permissions, de nouvelles nomenclatures)</span>
  - layouts <span style="color:red">Contient les layouts, ou organisation des différentes pages, en YAML</span>
- data <span style="color:red">Peut contenir des données</span>
- doc <span style="color:red">Contient la doc de votre sous-module</span>
- index.html
- README.md
- requirements.in <span style="color:red">Contient les requirements supplémentaires de votre sous-module</span>
- setup.py <span style="color:red">Fichier d'installation de votre sous-module</span>
- VERSION

### Utilisation d'un template

Pour faciliter la création de l'arborescence, j'ai crée un template à l'aide de [cookiecutter](https://cookiecutter.readthedocs.io/en/stable/). Pour le moment, celui-ci est accessible depuis la branche `feat/add-templates` dans le dossier `contrib/examples`.

Pour générer un projet de sous-module Modulator, il suffit de lancer les commandes suivantes:

```shell
git clone https://github.com/PnX-SI/gn_modulator.git
cd gn_modulator
git switch feat/add-templates # For now
cookiecutter contrib/examples/submodule_modulator_template
```

Une série de question/champ sont à remplir comme les suivants:

```plaintext
  [1/11] project_name (Minimum template for Modulator submodule): A test Project # Titre du projet
  [2/11] project_slug (a_test_project): # Nom du dossier contenant le projet
  [3/11] project_description (Lorem ipsum dolor sit amet, consectetur adipiscing
    elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
    ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
    commodo consequat.): # Description du projet
  [4/11] module_name (m_test): # Nom du module Python
  [5/11] module_desc (Module de test): # Description du module Modulator
  [6/11] module_picto (fa-road): # Pictogram du module affiché dans GeoNature
  [7/11] active_frontend [y/n] (y): # Si le module possède un frontend
  [8/11] db_schema_name (pr_test): # Nom du schema dans la basse de données
  [9/11] author (Anonymous): # Nom de l'auteur du module
  [10/11] author_email (anonym@example.com): # Adresse e-mail du contact
  [11/11] version (0.0.1): # Version du Module
```

Le dossier généré contient l'ensemble des fichiers pour obtenir un module fonctionnelle. Un modèle de données est déjà présent et s'articule sur la gestion de posts de blog.

### A la base de modulator : des fichiers de configurations/déclarations en YAML

Dans Modulator, à l'exception de la définition du modèle, l'entiéreté du module est construit à l'aide de fichier de déclaration/configuration suivant le language YAML.

Chaque fichier doit contenir au minimum les variables suivantes:

```yaml
type: module
code: m_herbier
title: Module de test
description: Module de test
```

- `type` permet d'indiquer le type de l'objet configuré(bof) : module, layout, export, schema
- `code` identifiant du fichier de configuration.
- `title` et `description` sont des métadonnées purement décorative pour décrire l'objet configuré

**<span style="color:red">Le nom du fichier doit correspondre avec les données dans les champs `code` et `type`. Par exemple, si le code est m_herbier et le type module, le nom du fichier doit être `m_herbier.module.yml`</span>**

### Configuration du module

Dans le code ci-dessous, vous trouverez un exemple du fichier de configuration d'un sous-module de Modulator.

```yaml
type: module
code: m_herbier
title: Module de test
description: Module de test

module:
  module_label: Herbier in Geonature
  module_desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  module_picto: fa-leaf
  active_frontend: true

features:
  - m_herbier.permissions

objects:
  releve:
    schema_code: m_herbier.releve
    cruved: "CRUIDE"

tree:
  releve:

pages_definition:
  releve:
    list:
      root: true
    edit:
    create:
      layout:
        code: m_herbier.releve_edit
    details:
```

#### Configuration Générale du module

Dans une première partie, on déclare le rôle du fichier yaml, i.e. ici un fichier de configuration pour un module. Pour cela, on utilise la variable `type` avec le valeur `module`.

La configuration du module s'effectue dans la variable `module`.

```yaml
module:
  module_label: Herbier in Geonature
  module_desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  module_picto: fa-leaf
  active_frontend: true
```

Les variables `module_label` et `module_desc` sont utilisés dans la page d'accueil de Modulator (voir Figure ci-dessous).

![Image](https://github.com/user-attachments/assets/9e7cd16e-7467-425a-9af8-43fd19f442f3)

**Notes** L'image affichée pour le module doit être placée dans le dossier `assets` dans un fichier au format JPEG avec le nom suivant : `module.jpg`.

La variable `module_picto` correspond à l'icone du module affiché dans le menu de GeoNature. La valeur correspond à l'identifiant CSS d'un icône proposé par la librairie FontAwesome dans sa version 4 (ou 5 ?).

<span style="color:red">[PAS SÛR]</span>La variabe `active_frontend` permet d'activer ou de désactiver l'accés du module sur le frontend(UI) de GeoNature.

#### Données d'initialisation

Des données comme les permissions ou de nouvelles nomenclatures peuvent s'avérer nécessaires au bon fonctionnment du module. Pour cela, Modulator intègre ce qu'il appelle des `features`. Une feature est déclaré dans un fichier `<code_module>.<nom_feature>.data.yml` (Voir section x.x pour la syntaxe des fichiers). Pour chaque feature crée, il faut la lister dans la variable `features` de la configuration du module.

```yaml
features:
  - <code_module>.<nom_feature>
```

#### Quels sont les objects définit et leur hiérarchie

Chaque objet du modèle définit dans le sous-module doit être listé dans la variable `objects`. Pour chaque objet, il faut indiquer le code utilisé dans le fichier de schema de l'objet (variable `schema_code`) et les permissions qui sont associés à ce dernier (variable `cruved`).

```yaml
objects:
  objet_1:
    schema_code: <module_code>.objet_1
    cruved: CR
```

La hiérachie des objets entre eux est indiqué dans la variable `tree`. Si `objet_1` est l'enfant de `objet_2`, alors utilise le code suivant:

```yaml
tree:
  objet_1:
    objet_2:
```

#### Définiton du frontend

Dans le frontend de modulator, chaque objet est associé à un ensemble de page. Une page dédiée à la création d'un objet `create`, à l'édition `edit`, à l'affichage des enregistrements `list` et au details d'un enregistrement de l'objet `details`.

Pour définir les pages du frontend, il faut utiliser la variable `pages_definition`. Cette dernière est une liste des objets que l'on veut accéder dans le frontend.

```yaml
pages_definition:
  objet_1:
  objet_2:
```

Puis, par objet, on définit les pages accessibles comme ceci:

```yaml
pages_definition:
  objet_1:
    create:
  objet_2:
    list:
    details:
```

Si la page `create` pour l'`objet_1` est definit, alors un fichier `m_herbier.objet1_create.layout.yml` doit être créer dans le dossier `layout`. (Voir section pour la définition d'un layout)

### Définition du modèle de données

Pour déclarer le modèle de votre sous-module, il faut déclarer les tables qui le compose dans trois types de fichiers différents:

- Fichier Python avec la définition SQLAlchemy des tables
- Fichier Python des révisions alembic
- Fichiers YAML avec la définition des tables

Dans ce document, nous utiliserons comme exemple le modèle d'un herbier. Un herbier consiste en un collection d'herbe. Pour cela, nous avons choisi d'utiliser un objet `Releve` définit par les champs suivants:

- `id_releve` : Identifiant du Relevé
- `uuid_releve` : UUID du Relevé (utile pour les medias)
- `id_herbe` : cd_nom de l'herbe collecté
- `date_releve` : date du relevé
- `id_role` : identifiant du collecteur dans _utilisateurs.t_roles_
- `medias` : photos associées
- `geom_releve` : Geometrie du lieu de collecte

#### Définition SQLAlchemy des tables

Si vous êtes habitués au développement de module GeoNature, vous ne serez pas depaysé. Pour les autres, je vous invites à vous diriger sur la documentation de SQLAlchemy.

La déclaration des objets/tables en SQLAlchemy s'effectue dans le fichier `models.py` dans le dossier `backend`.

Ci-dessous, la déclaration du modèle pour le `Relevé`.

```python
import uuid
from geoalchemy2 import Geometry

from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy import func

from geonature.utils.env import db
from pypnusershub.db.models import User
from geonature.core.gn_commons.models import TMedias
from apptax.taxonomie.models import Taxref


class Releve(db.Model):
    __tablename__ = "releve"
    __table_args__ = {"schema": "pr_herbier"}

    id_releve = db.Column(db.Integer, primary_key=True)
    uuid_releve = db.Column(UUID(as_uuid=True), default=uuid.uuid4())

    id_herbe = db.Column(
        db.Integer, db.ForeignKey("taxonomie.taxref.cd_nom"), nullable=False
    )
    herbe = db.relationship(Taxref, foreign_keys=[id_herbe])

    date_releve = db.Column(db.Date, nullable=False, server_default=func.now())

    id_role = db.Column(db.Integer, db.ForeignKey("utilisateurs.t_roles.id_role"))
    role = db.relationship(User)

    medias = db.relationship(
        TMedias,
        primaryjoin=TMedias.uuid_attached_row == uuid_releve,
        foreign_keys=[TMedias.uuid_attached_row],
        cascade="all",
        lazy="select",
    )

    geom_releve = db.Column(Geometry("GEOMETRY", 4326), nullable=False)

```

#### Révisions alembic

Tout comme la déclaration du modèle avec SQLAlchemy, l'utilisation des révisions Alembic ne différe de celle dans GeoNature. Les révisions alembics permettent d'appliquer des changements (methode `upgrade()`) sur la base de données mais aussi de les annuler (methode `downgrade`).

**<span style="color:red">ATTENTION : </span>** Il est nécessaire (**<span style="color:red">uniquement dans la première révision !!</span>**) d'indiquer la branche `modulator` dans la variable `branch_labels`

Ci-dessous, un exemple de la révision qui crée la table `releve`.

```python
"""init sous-module m_herbier

Revision ID: sdfsdgseeg62562
Create Date: 2023-02-01 12:48:24.613956
"""
import uuid
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = "sdfsdgseeg62562"  # TODO : Change it !!!
down_revision = None
branch_labels = "m_herbier"
depends_on = "modulator"


def upgrade():
    op.execute("create schema pr_herbier")
    op.create_table(
        "releve",
        sa.Column("id_releve", sa.Integer, primary_key=True),
        sa.Column("uuid_releve", UUID(as_uuid=True), default=uuid.uuid4),
        sa.Column(
            "id_herbe",
            sa.Integer,
            sa.ForeignKey("taxonomie.taxref.cd_nom"),
            nullable=False,
        ),
        sa.Column("date_releve", sa.Date, nullable=False, server_default=sa.func.now()),
        sa.Column(
            "id_role",
            sa.Integer,
            sa.ForeignKey("utilisateurs.t_roles.id_role"),
            nullable=False,
        ),
        sa.Column("geom_releve", Geometry("GEOMETRY", 4326), nullable=False),
        schema="pr_herbier",
    )


def downgrade():
    op.drop_table("releve", schema="pr_herbier")
    op.execute("drop schema pr_herbier")

```

#### Définition des tables/schema dans des fichiers YAML

Pour chaque table définit dans votre modèle, vous devez définir un `schema`. Chaque schema doit être stocker dans un fichier `yaml` dans le dossier `config/definitions` avec le nom de fichier suivant `<code_module>.<nom_table>.schema.yml`.

Comme dans le reste des fichiers YAML de Modulator, nous devons définir le `type` à `schema`. Le code doit correspondre au format suivant : `<code_module>.<nom_table>`.

Dans le définition deux variables principales sont à déclarer: `meta` et `properties`. `meta` contient toutes les méta-données associé à la table/objets comme la chemin d'import de la classe dans le backend, le genre (Masculin ou féminin) de l'objet définit. Dans `properties`, on peut indiquer des informations additionnels au colonnes présents dans la table comme le label, la description qui seront réutilisés dans la génération automatique des formulaires.

Ci-dessous, un exemple de définition de schema pour l'objet Relevé

```yaml
type: schema
code: m_herbier.releve
title: schema releve
description: Définition du schema pour un releve
meta:
  model: m_herbier.models.Releve
  module_code: m_herbier
  genre: M
  label: Relevé
  labels: Relevés
  label_field_name: id_herbe
  geometry_field_name: geom_releve
  unique:
    - id_releve
    - uuid_releve
  check_cruved: true
  import_excluded_fields:
    - id_releve
    - medias
    - herbe
properties:
  id_releve:
    title: ID du Relevé
  uuid_releve:
    title: UUID du releve
  id_herbe:
    title: id_herbe
    schema_code: tax.taxref
  date_releve:
    title: Date du relevé
  id_role:
    title: Utilisateur qui a fait le relevé
    schema_code: user.role
  medias:
    title: "photo de l'herbe"
  geom_releve:
    title: Géométrie
```

##### `meta`

| Variable                   | Description                                                                        |
| -------------------------- | ---------------------------------------------------------------------------------- |
| **model**                  | chemin d'import de la classe Python qui définit la table                           |
| **module_code**            | code du module                                                                     |
| **genre**                  | genre de l'objet définit                                                           |
| **label,labels**           | Label de l'objet au singulier et au pluriel                                        |
| **unique**                 | Colonnes qui permettent d'identifier l'objet de manière unique                     |
| **check_cruved**           | Si nécessite de controler les permissions de l'utilisateur                         |
| **geometry_field_name**    | Si géométrie, quelle colonne de la table contient la geométrie d'un enregistrement |
| **import_excluded_fields** | Colonne de la table ignoré lors de l'import                                        |

##### `properties`

| Variable        | Description                    |
| --------------- | ------------------------------ |
| **title**       | Label affiché dans le frontend |
| **description** | Aide affichée                  |
| **schema_code** | (NSP)                          |

### Définition des permissions

(Créer/modifier le fichier features pour les permissions)

```yaml
type: data
code: m_herbier.permissions
title: Data permissions m_herbier
description: Permissions disponibles pour le module m_herbier
items:
  - schema_code: perm.perm_dispo
    defaults:
      id_module: m_herbier
    keys: [id_object, id_action, scope_filter, label]
    items:
      - [ALL, C, true, "Créer et importer des relevés"]
      - [ALL, R, true, "Voir les relevés"]
      - [ALL, U, true, "Modifier les relevés"]
      - [ALL, D, true, "Supprimer des relevés"]
      - [ALL, E, true, "Exporter des relevés"]
```

**Appliquer des changements de permissions** Modifier le fichier de permissions dans le dossier `features`, puis lancer la commande : `geonature modulator features <module_code>.<nom_feature>`.

#### Base d'un layout

```yaml
type: layout
code: <code_module>.<objet/table>_<type_page>
title: Titre layout
description: Description du layout

layout: <description du layout>
```

#### Création de formulaire de saisis et d'édition d'un objet

```yaml
type: layout
code: m_herbier.releve_edit
title: Layout site edit
description: Layout pour la liste de auteurs

layout:
  height_auto: true
  items:
    code: utils.object_form_map
    template_params:
      object_code: releve
      layout:
        items:
          - overflow: true
            items:
              - key: id_herbe
                title: Herbe
                type: list_form
                object_code: tax.taxsearch
                module_code: MODULATOR
                reload_on_search: true
                page_size: 20
              - date_releve
              - id_role
              - label: __f__ `Médias (${data?.medias?.length || 0})`
                items:
                  items:
                    - type: dyn_form
                      key: medias
                      type_widget: medias
                      schema_dot_table: pr_herbier.releve
                      details: []
      zoom: "__f__o.value(x) ? 12 : null"
      skip_ref_layers: []
      keep_zoom_center: __f__!o.value(x)
      geojsons:
        layout:
          - type: object
            hidden: __f__!context.map_params?.bounds_filter_value
            display: geojson
            object_code: ref_geo.point
            module_code: MODULATOR
            title: PK / PR
            activate: false
            zoom_min: 12
```

#### Afficher les objets saisies

```yaml
type: layout
code: m_herbier.releve_list
title: Layout site list
description: Layout pour la liste de auteurs

layout:
  height_auto: true
  direction: row
  object_code: releve
  title: "Liste des relevés"
  items:
    - height_auto: false
      overflow: true
      items:
        - code: utils.button_create
        - type: button
          description: Exporter les relevés
          color: primary
          flex: "0"
          icon: download
          hidden: __f__!o.is_action_allowed(x, 'E')
          action:
            type: modal
            modal_name: exports
        - type: modal
          flex: "0"
          modal_name: exports
          items:
            - title: Exports pour les relevés
            - type: button
              flex: "0"
              title: "Export des relevés"
              description: Télécharger les relevés (les filtres sont appliqués)
              href: __f__o.url_export(x, 'm_herbier.releve')
        - type: button
          flex: "0"
          icon: upload
          color: primary
          description: Importer des relevés
          action:
            type: modal
            modal_name: import
          # hidden: __f__!o.is_action_allowed(x, 'I')
        - type: modal
          modal_name: import
          items:
            type: import
        - type: object
          display: table
          items: [id_herbe, date_releve, id_role]
    - type: object
      object_code: releve
      items:
        - type: map
          key: __f__o.geometry_field_name(x)
          zoom: 5
          skip_ref_layers: []
          keep_zoom_center: __f__!o.value(x)
          items:
            layout:
              - type: object
                hidden: __f__!context.map_params?.bounds_filter_value
                display: geojson
                object_code: ref_geo.point
                module_code: MODULATOR
                title: PK / PR
                activate: false
                zoom_min: 12
```

#### Afficher en détail un objet saisi

```yaml
type: layout
code: m_herbier.releve_details
title: Layout post list
description: Layout pour la liste de posts

layout:
  direction: row
  items:
    - type: section
      items:
        - code: utils.object_details
          template_params:
            object_code: releve
            layout: [id_herbe, date_releve]
```

#### Page par défaut

```yaml
pages_definition:
  releve:
    list:
      root: true
```

### Installer un sous-module

```shell
geonature modulator install -p <cheminverssousmodule>
```

### Désinstaller un sous-module

```shell
geonature modulator remove -p <cheminverssousmodule>
```

### Inserer des données déclarées dans les features manuellement

```shell
geonature modulator features <code_module>.<nom_feature>
```

### Import de données venant d'un fichier CSV

```shell
geonature modulator import -s <schemacode> -d <fichier>
```

### Check les fichiers YAML

```shell
geonature modulator check
```
